### PR TITLE
Do not override headers

### PR DESCRIPTION
**Pull request by nileshgulia1**

### CODE REVIEW

**Review by tiberiuichim — CHANGES_REQUESTED** [review]
Keep the `...request` spread, then overwrite the headers

**Review by tiberiuichim — APPROVED** [review]
LGTM, nitpicking, you should really must very much for sure there's no other way but: integrate eslint in your text editor.

**Comment by nileshgulia1** [comment]
Thanks. I have integrated it, but somehow its not taking the project eslint
configuration. Need to reconfigure it though.

**Comment by tiberiuichim** [comment]
@nileshgulia1 It happens, eslint is a finicky thing, it breaks all the time for me so I pay special attention to have it running at all time.

What I do to have it running is this:

- make sure that I edit the addon in the proper context (it needs to be in the src/addons folder of the frontend)
- run eslint `src/addons/...path/to/file` from the Volto project to see if there's any problems with eslint. It will report them.

**Pull request merged**
